In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
df = pd.read_excel(r'C:\Users\schai\Downloads\1st, 2nd - Pandas\1st, 2nd - Pandas\Country GDP Analysis- project\data.xlsx')

In [4]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [5]:
df.shape

(195, 5)

In [6]:
df.size

975

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
id(df)

3187867382320

In [9]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [11]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [12]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [13]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [14]:
df.head(7)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
6,Armenia,ARM,13.308,41.9,Lower middle income

In [15]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [16]:
df.tail(3)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [17]:
df.tail(9)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
186,Vietnam,VNM,15.537,43.9,Lower middle income
187,Vanuatu,VUT,26.739,11.3,Lower middle income
188,West Bank and Gaza,PSE,30.394,46.6,Lower middle income
189,Samoa,WSM,26.172,15.3,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [18]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [19]:
df.isna()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [20]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [21]:
df[10:30]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income
20,Belarus,BLR,12.500,54.17000,Upper middle income
21,Belize,BLZ,23.092,33.60000,Upper middle income
22,Bermuda,BMU,10.400,95.30000,High income
23,Bolivia,BOL,24.236,36.94000,Lower middle income
24,Brazil,BRA,14.931,51.04000,Upper middle income
25,Barbados,BRB,12.188,73.00000,High income
26,Brunei Darussalam,BRN,16.405,64.50000,High income
27,Bhutan,BTN,18.134,29.90000,Lower middle income
28,Botswana,BWA,25.267,15.00000,Upper middle income
29,Central African Republic,CAF,34.076,3.50000,Low income

In [22]:
df[0:10:2]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
2,Angola,AGO,45.985,19.1,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
8,Australia,AUS,13.200,83.0,High income

In [23]:
df[:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [24]:
df[:5]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [25]:
df[0:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [26]:
df[::]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [27]:
df[::1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [28]:
df[::-1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
191,South Africa,ZAF,20.850,46.5,Upper middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
...,...,...,...,...,...
4,United Arab Emirates,ARE,11.044,88.0,High income
3,Albania,ALB,12.877,57.2,Upper middle income
2,Angola,AGO,45.985,19.1,Upper middle income
1,Afghanistan,AFG,35.253,5.9,Low income
0,Aruba,ABW,10.244,78.9,High income

In [29]:
df[::-50]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5000,Low income
144,French Polynesia,PYF,16.393,56.8000,High income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
44,Czech Republic,CZE,10.200,74.1104,High income

In [30]:
df[::-25]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5000,Low income
169,Thailand,THA,11.041,28.9400,Upper middle income
144,French Polynesia,PYF,16.393,56.8000,High income
119,Mongolia,MNG,24.275,20.0000,Upper middle income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
69,Grenada,GRD,19.334,35.0000,Upper middle income
44,Czech Republic,CZE,10.200,74.1104,High income
19,Bosnia and Herzegovina,BIH,9.062,57.7900,Upper middle income

In [31]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [32]:
df['IncomeGroup']

0              High income
1               Low income
2      Upper middle income
3      Upper middle income
4              High income
              ...
190    Lower middle income
191    Upper middle income
192             Low income
193    Lower middle income
194             Low income
Name: IncomeGroup, Length: 195, dtype: object

In [33]:
df[['InternetUsers','IncomeGroup']]

     InternetUsers          IncomeGroup
0             78.9          High income
1              5.9           Low income
2             19.1  Upper middle income
3             57.2  Upper middle income
4             88.0          High income
..             ...                  ...
190           20.0  Lower middle income
191           46.5  Upper middle income
192            2.2           Low income
193           15.4  Lower middle income
194           18.5           Low income

[195 rows x 2 columns]

In [34]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [35]:
df_cat = df[['CountryName', 'CountryCode', 'IncomeGroup']]

In [36]:
df_cat

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [37]:
df_num = df[['BirthRate', 'InternetUsers']]

In [38]:
df_num

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [39]:
df[(df.BirthRate < 40) & (df.InternetUsers>50)]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.90,High income
3,Albania,ALB,12.877,57.20,Upper middle income
4,United Arab Emirates,ARE,11.044,88.00,High income
5,Argentina,ARG,17.716,59.90,High income
7,Antigua and Barbuda,ATG,16.447,63.40,High income
...,...,...,...,...,...
174,Trinidad and Tobago,TTO,14.590,63.80,High income
180,Uruguay,URY,14.374,57.69,High income
181,United States,USA,12.500,84.20,High income
183,St. Vincent and the Grenadines,VCT,16.306,52.00,Upper middle income
184,"Venezuela, RB",VEN,19.842,54.90,High income

In [40]:
df[df.BirthRate > 40]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
11,Burundi,BDI,44.151,1.3,Low income
14,Burkina Faso,BFA,40.551,9.1,Low income
65,"Gambia, The",GMB,42.525,14.0,Low income
115,Mali,MLI,44.138,3.5,Low income
127,Niger,NER,49.661,1.7,Low income
128,Nigeria,NGA,40.045,38.0,Lower middle income
156,Somalia,SOM,43.891,1.5,Low income
167,Chad,TCD,45.745,2.3,Low income
178,Uganda,UGA,43.474,16.2,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income

In [41]:
df.columns = ('A','B','C','D','E')

In [42]:
df.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [43]:
df['A']

0                     Aruba
1               Afghanistan
2                    Angola
3                   Albania
4      United Arab Emirates
               ...
190             Yemen, Rep.
191            South Africa
192        Congo, Dem. Rep.
193                  Zambia
194                Zimbabwe
Name: A, Length: 195, dtype: object

In [44]:
df.columns = ('CountryName', 'CountryCode', 'BirthRate', 'InternetUsers','IncomeGroup')

In [45]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [46]:
df['avg'] = df.BirthRate * df.InternetUsers

In [47]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup', 'avg'],
      dtype='object')

In [48]:
df.describe()

        BirthRate  InternetUsers          avg
count  195.000000     195.000000   195.000000
mean    21.469928      42.076471   653.559009
std     10.605467      29.030788   351.553521
min      7.900000       0.900000    28.990400
25%     12.120500      14.520000   361.263300
50%     19.680000      41.000000   682.074300
75%     29.759500      66.225000   892.690170
max     49.661000      96.546800  1552.589500

In [49]:
print(df.shape)
print(df_cat.shape)
print(df_num.shape)

(195, 6)
(195, 3)
(195, 2)

In [50]:
df_cat.describe()

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

In [51]:
print(len(df_cat.describe()))

4

In [52]:
df[df['InternetUsers']<20]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,avg
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
11,Burundi,BDI,44.151,1.3,Low income,57.3963
13,Benin,BEN,36.440,4.9,Low income,178.5560
14,Burkina Faso,BFA,40.551,9.1,Low income,369.0141
...,...,...,...,...,...,...
187,Vanuatu,VUT,26.739,11.3,Lower middle income,302.1507
189,Samoa,WSM,26.172,15.3,Lower middle income,400.4316
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668
193,Zambia,ZMB,40.471,15.4,Lower middle income,623.2534
194,Zimbabwe,ZWE,35.715,18.5,Low income,660.7275

In [53]:
df[df['BirthRate']>30]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,avg
1,Afghanistan,AFG,35.253,5.90,Low income,207.99270
2,Angola,AGO,45.985,19.10,Upper middle income,878.31350
11,Burundi,BDI,44.151,1.30,Low income,57.39630
13,Benin,BEN,36.440,4.90,Low income,178.55600
14,Burkina Faso,BFA,40.551,9.10,Low income,369.01410
29,Central African Republic,CAF,34.076,3.50,Low income,119.26600
34,Cote d'Ivoire,CIV,37.320,8.40,Lower middle income,313.48800
35,Cameroon,CMR,37.236,6.40,Lower middle income,238.31040
36,"Congo, Rep.",COG,37.011,6.60,Lower middle income,244.27260
38,Comoros,COM,34.326,6.50,Low income,223.11900
52,Eritrea,ERI,34.800,0.90,Low income,31.32000
55,Ethiopia,ETH,32.925,1.90,Low income,62.55750
60,Gabon,GAB,30.555,9.20,Upper middle income,281.10600
63,Ghana,GHA,33.131,12.30,Lower middle income,407.51130
64,Guinea,GIN,37.337,1.60,Low income,59.73920
65,"Gambia, The",GMB,42.525,14.00,Low income,595.35000
66,Guinea-Bissau,GNB,37.503,3.10,Low income,116.25930
67,Equatorial Guinea,GNQ,35.362,16.40,High income,579.93680
83,Iraq,IRQ,31.093,9.20,Upper middle income,286.05560
91,Kenya,KEN,35.194,39.00,Lower middle income,1372.56600
99,Liberia,LBR,35.521,3.20,Low income,113.66720
111,Madagascar,MDG,34.686,3.00,Low income,104.05800
115,Mali,MLI,44.138,3.50,Low income,154.48300
120,Mozambique,MOZ,39.705,5.40,Low income,214.40700
121,Mauritania,MRT,33.801,6.20,Lower middle income,209.56620
123,Malawi,MWI,39.459,5.05,Low income,199.26795
127,Niger,NER,49.661,1.70,Low income,84.42370
128,Nigeria,NGA,40.045,38.00,Lower middle income,1521.71000
148,Rwanda,RWA,32.689,9.00,Low income,294.20100
150,Sudan,SDN,33.477,22.70,Lower middle income,759.92790
151,Senegal,SEN,38.533,13.10,Lower middle income,504.78230
153,Solomon Islands,SLB,30.578,8.00,Lower middle income,244.62400
154,Sierra Leone,SLE,36.729,1.70,Low income,62.43930
156,Somalia,SOM,43.891,1.50,Low income,65.83650
158,South Sudan,SSD,37.126,14.10,Low income,523.47660
159,Sao Tome and Principe,STP,34.537,23.00,Lower middle income,794.35100
164,Swaziland,SWZ,30.093,24.70,Lower middle income,743.29710
167,Chad,TCD,45.745,2.30,Low income,105.21350
168,Togo,TGO,36.080,4.50,Low income,162.36000
170,Tajikistan,TJK,30.792,16.00,Lower middle income,492.67200
172,Timor-Leste,TLS,35.755,1.10,Lower middle income,39.33050
177,Tanzania,TZA,39.518,4.40,Low income,173.87920
178,Uganda,UGA,43.474,16.20,Low income,704.27880
188,West Bank and Gaza,PSE,30.394,46.60,Lower middle income,1416.36040
190,"Yemen, Rep.",YEM,32.947,20.00,Lower middle income,658.94000
192,"Congo, Dem. Rep.",COD,42.394,2.20,Low income,93.26680
193,Zambia,ZMB,40.471,15.40,Lower middle income,623.25340
194,Zimbabwe,ZWE,35.715,18.50,Low income,660.72750

In [54]:
df[((df.InternetUsers>30) & (df.BirthRate < 30))]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,avg
0,Aruba,ABW,10.244,78.9,High income,808.2516
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720
5,Argentina,ARG,17.716,59.9,High income,1061.1884
6,Armenia,ARM,13.308,41.9,Lower middle income,557.6052
...,...,...,...,...,...,...
183,St. Vincent and the Grenadines,VCT,16.306,52.0,Upper middle income,847.9120
184,"Venezuela, RB",VEN,19.842,54.9,High income,1089.3258
185,Virgin Islands (U.S.),VIR,10.700,45.3,High income,484.7100
186,Vietnam,VNM,15.537,43.9,Lower middle income,682.0743
191,South Africa,ZAF,20.850,46.5,Upper middle income,969.5250

In [55]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup', 'avg'],
      dtype='object')

In [56]:
df = df.drop('avg',axis=1 )

In [57]:
df['add'] = df.BirthRate + df.InternetUsers

In [58]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,add
0,Aruba,ABW,10.244,78.9,High income,89.144
1,Afghanistan,AFG,35.253,5.9,Low income,41.153
2,Angola,AGO,45.985,19.1,Upper middle income,65.085
3,Albania,ALB,12.877,57.2,Upper middle income,70.077
4,United Arab Emirates,ARE,11.044,88.0,High income,99.044
...,...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income,52.947
191,South Africa,ZAF,20.850,46.5,Upper middle income,67.350
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,44.594
193,Zambia,ZMB,40.471,15.4,Lower middle income,55.871
194,Zimbabwe,ZWE,35.715,18.5,Low income,54.215

In [59]:
df = df.drop('add',axis=1)

In [60]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [61]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [62]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [63]:
df[df.IncomeGroup == 'High income']

               CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0                    Aruba         ABW     10.244          78.90  High income
4     United Arab Emirates         ARE     11.044          88.00  High income
5                Argentina         ARG     17.716          59.90  High income
7      Antigua and Barbuda         ATG     16.447          63.40  High income
8                Australia         AUS     13.200          83.00  High income
..                     ...         ...        ...            ...          ...
174    Trinidad and Tobago         TTO     14.590          63.80  High income
180                Uruguay         URY     14.374          57.69  High income
181          United States         USA     12.500          84.20  High income
184          Venezuela, RB         VEN     19.842          54.90  High income
185  Virgin Islands (U.S.)         VIR     10.700          45.30  High income

[67 rows x 5 columns]

In [64]:
df[(df.BirthRate)<30]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
...,...,...,...,...,...
185,Virgin Islands (U.S.),VIR,10.700,45.3,High income
186,Vietnam,VNM,15.537,43.9,Lower middle income
187,Vanuatu,VUT,26.739,11.3,Lower middle income
189,Samoa,WSM,26.172,15.3,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income

In [65]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [68]:
df.nunique()

CountryName      195
CountryCode      195
BirthRate        177
InternetUsers    181
IncomeGroup        4
dtype: int64

In [71]:
df['IncomeGroup'].unique()

array(['High income', 'Low income', 'Upper middle income',
       'Lower middle income'], dtype=object)

In [70]:
df['IncomeGroup'].nunique()

4